---
platform: linux
#image: docker:///cloudfoundry/bosh-lite-ci
image: docker:///bosh/os-image-stemcell-builder
inputs:
- name: bosh-src
- name: stemcell-version
run:
  path: bosh-src/ci/pipelines/stemcells/tasks/build-stemcell.sh
